-- Menu Controller Unit Tests
-- Generated by curd command. Run with: luajit tests/unit/controllers/MenuSpec.lua

package.path="/var/www/web/my-openresty/?.lua;;"..package.path
package.cpath="/var/www/web/my-openresty/?.so;;"..package.cpath

local tests_passed=0
local tests_failed=0

local function assert_eq(exp,act,name)
    if exp==act then
        print("✓ PASS: "..name)
        tests_passed=tests_passed+1
    else
        print("✗ FAIL: "..name)
        print("  Expected: "..tostring(exp))
        print("  Actual:   "..tostring(act))
        tests_failed=tests_failed+1
    end
end

print("=============================================================")
print("Menu Controller Unit Tests")
print("=============================================================")
print()

-- Test: controller should load model
print("Test: controller structure")
local C=require("app.controllers.Menu")
assert_eq("table",type(C),"controller should be table")
assert_eq("function",type(C.list),"list() should be function")
assert_eq("function",type(C.detail),"detail() should be function")
assert_eq("function",type(C.create),"create() should be function")
assert_eq("function",type(C.update),"update() should be function")
assert_eq("function",type(C.delete),"delete() should be function")
assert_eq("function",type(C.get_params),"get_params() should be function")
print()

-- Test: mock request
print("Test: mock request handling")
local mock={get={page="1",pageSize="10"},post={},json=function()end}
setmetatable(mock,{__index=function(t,k) return function() end end})
assert_eq("function",type(mock.get_params),"get_params should be callable")
print()

-- Test: list() should call model
print("Test: list() interface")
assert_eq("function",type(C.list),"list should be function")
print()

-- Test: detail() should require id
print("Test: detail() interface")
assert_eq("function",type(C.detail),"detail should be function")
print()

-- Test: create() interface
print("Test: create() interface")
assert_eq("function",type(C.create),"create should be function")
print()

-- Test: update() interface
print("Test: update() interface")
assert_eq("function",type(C.update),"update should be function")
print()

-- Test: delete() interface
print("Test: delete() interface")
assert_eq("function",type(C.delete),"delete should be function")
print()

print("="..string.rep("=",60)..")
print("Test Results")
print("="..string.rep("=",60)..")
print("Passed: "..tests_passed)
print("Failed: "..tests_failed)
print()
if tests_failed>0 then os.exit(1) end
