-- MenuModel Unit Tests
-- Generated by curd command. Run with: luajit tests/unit/models/menu_spec.lua

package.path="/var/www/web/my-openresty/?.lua;;"..package.path
package.cpath="/var/www/web/my-openresty/?.so;;"..package.cpath

local Test=require("app.lib.test")
local MenuModel=require("app.models.MenuModel")

local tests_passed=0
local tests_failed=0

local function assert_eq(exp,act,name)
    if exp==act then
        print("✓ PASS: "..name)
        tests_passed=tests_passed+1
    else
        print("✗ FAIL: "..name)
        print("  Expected: "..tostring(exp))
        print("  Actual:   "..tostring(act))
        tests_failed=tests_failed+1
    end
end

print("=============================================================")
print("MenuModel Unit Tests")
print("=============================================================")
print()

-- Test: new()
print("Test: new()")
local m=MenuModel:new()
assert_eq("menu",m._TABLE,"new() should set table name")
assert_eq(true,m~=nil,"new() should return instance")
print()

-- Test: list() should return table
print("Test: list()")
local list=m:list({page=1,pageSize=10})
assert_eq("table",type(list),"list() should return table")
print()

-- Test: count() should return number
print("Test: count()")
local cnt=m:count({})
assert_eq("number",type(cnt),"count() should return number")
print()

-- Test: detail() with id
print("Test: detail()")
local d=m:detail({id=1})
assert_eq("table",type(d),"detail() should return table or nil")
print()

-- Test: create() should return id
print("Test: create()")
local id=m:create({username="test_1770271040",phone="1040"})
assert_eq("number",type(id),"create() should return id")
print()

-- Test: update() should return boolean
print("Test: update()")
local ok=m:update({id=1,username="updated"})
assert_eq("boolean",type(ok),"update() should return boolean")
print()

-- Test: delete() should return boolean
print("Test: delete()")
local ok=m:delete({id=1})
assert_eq("boolean",type(ok),"delete() should return boolean")
print()

print("="..string.rep("=",60)..")
print("Test Results")
print("="..string.rep("=",60)..")
print("Passed: "..tests_passed)
print("Failed: "..tests_failed)
print()
if tests_failed>0 then os.exit(1) end
