#!/bin/bash
# Menu Integration Tests
# Generated by curd command

BASE_URL=${BASE_URL:-http://localhost:8080}
TABLE="menu"

echo "============================================================"
echo "Menu Integration Tests"
echo "============================================================"
echo "Base URL: $BASE_URL"
echo ""

passed=0
failed=0

test_api() {
    local method=$1
    local endpoint=$2
    local data=$3
    local name=$4

    echo "Test: $name"
    if [ -n "$data" ]; then
        response=$(curl -s -X $method "$BASE_URL$endpoint" -H "Content-Type: application/json" -d '"$data')
    else
        response=$(curl -s -X $method "$BASE_URL$endpoint")
    fi

    if echo "$response" | grep -q "success"; then
        echo "✓ PASS: $name"
        ((passed++))
    else
        echo "✗ FAIL: $name"
        echo "  Response: $response"
        ((failed++))
    fi
    echo ""
}

echo "Test: List $TABLE"
test_api "GET" "/menu/list" "" "List menu"

echo "Test: Create $TABLE"
test_api "POST" "/menu/create" '{"username":"test_1770271040","phone":"1040","role_id":1}' "Create menu"

echo "Test: Detail $TABLE"
test_api "GET" "/menu/detail?id=1" "" "Detail menu"

echo "Test: Update $TABLE"
test_api "POST" "/menu/update" '{"id":1,"username":"updated"}' "Update menu"

echo "Test: Delete $TABLE"
test_api "POST" "/menu/delete" '{"id":1}' "Delete menu"

echo "============================================================"
echo "Test Results"
echo "============================================================"
echo "Passed: $passed"
echo "Failed: $failed"
echo ""

if [ $failed -gt 0 ]; then
    echo "Some tests failed!"
    exit 1
else
    echo "All tests passed!"
    exit 0
fi
